# Generated by Django 5.1.7 on 2025-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(upload_to="media/menu_images"),
        ),
    ]
